### ISSUE TITLE
Adressevalg

### ISSUE THREAD

**Issue by steinkjer73** [prebusmaximus/tibwidget-ir#4]
**Beskriv feilen**
Valg av adresse funker ikke, kun ene adressen som kommer opp. Endrer jeg til den andre adressen og lagrer så skjer det ikke noe..

A high-level summary or description of the problem that you're facing.
-->

**Hvordan reprodusere**

**Skjermbilder eller video**

**Miljø informasjon**

 - Platform : 
 - TibWidget Versjon:
 - Operativsystem:

**Tilleggsinformasjon**

**Comment by prebusmaximus** [comment]
Det var rart. Skal se på det sammen med den andre bug'en som fikses i helgen nå. Du får tilbakemelding på denne tråden når dette er oppdatert og oppdatering sendes ut automatisk.

**Comment by prebusmaximus** [comment]
@steinkjer73 jeg har forsøkt å kontakte deg via Facebook Messenger, kan du være snill å sende meg en e-post på support@tibwidget.eu for en kjapp dialog rundt problemet ditt?
